/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmployeesImport } from './routes/employees'
import { Route as CafesImport } from './routes/cafes'
import { Route as IndexImport } from './routes/index'
import { Route as EmployeeAddIndexImport } from './routes/employee/add/index'
import { Route as CafeAddIndexImport } from './routes/cafe/add/index'
import { Route as EmployeeEditEmployeeIdImport } from './routes/employee/edit/$employeeId'
import { Route as CafeEditCafeIdImport } from './routes/cafe/edit/$cafeId'

// Create/Update Routes

const EmployeesRoute = EmployeesImport.update({
  path: '/employees',
  getParentRoute: () => rootRoute,
} as any)

const CafesRoute = CafesImport.update({
  path: '/cafes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeAddIndexRoute = EmployeeAddIndexImport.update({
  path: '/employee/add/',
  getParentRoute: () => rootRoute,
} as any)

const CafeAddIndexRoute = CafeAddIndexImport.update({
  path: '/cafe/add/',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeEditEmployeeIdRoute = EmployeeEditEmployeeIdImport.update({
  path: '/employee/edit/$employeeId',
  getParentRoute: () => rootRoute,
} as any)

const CafeEditCafeIdRoute = CafeEditCafeIdImport.update({
  path: '/cafe/edit/$cafeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cafes': {
      id: '/cafes'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesImport
      parentRoute: typeof rootRoute
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesImport
      parentRoute: typeof rootRoute
    }
    '/cafe/edit/$cafeId': {
      id: '/cafe/edit/$cafeId'
      path: '/cafe/edit/$cafeId'
      fullPath: '/cafe/edit/$cafeId'
      preLoaderRoute: typeof CafeEditCafeIdImport
      parentRoute: typeof rootRoute
    }
    '/employee/edit/$employeeId': {
      id: '/employee/edit/$employeeId'
      path: '/employee/edit/$employeeId'
      fullPath: '/employee/edit/$employeeId'
      preLoaderRoute: typeof EmployeeEditEmployeeIdImport
      parentRoute: typeof rootRoute
    }
    '/cafe/add/': {
      id: '/cafe/add/'
      path: '/cafe/add'
      fullPath: '/cafe/add'
      preLoaderRoute: typeof CafeAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/employee/add/': {
      id: '/employee/add/'
      path: '/employee/add'
      fullPath: '/employee/add'
      preLoaderRoute: typeof EmployeeAddIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/employees': typeof EmployeesRoute
  '/cafe/edit/$cafeId': typeof CafeEditCafeIdRoute
  '/employee/edit/$employeeId': typeof EmployeeEditEmployeeIdRoute
  '/cafe/add': typeof CafeAddIndexRoute
  '/employee/add': typeof EmployeeAddIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/employees': typeof EmployeesRoute
  '/cafe/edit/$cafeId': typeof CafeEditCafeIdRoute
  '/employee/edit/$employeeId': typeof EmployeeEditEmployeeIdRoute
  '/cafe/add': typeof CafeAddIndexRoute
  '/employee/add': typeof EmployeeAddIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/employees': typeof EmployeesRoute
  '/cafe/edit/$cafeId': typeof CafeEditCafeIdRoute
  '/employee/edit/$employeeId': typeof EmployeeEditEmployeeIdRoute
  '/cafe/add/': typeof CafeAddIndexRoute
  '/employee/add/': typeof EmployeeAddIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cafes'
    | '/employees'
    | '/cafe/edit/$cafeId'
    | '/employee/edit/$employeeId'
    | '/cafe/add'
    | '/employee/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cafes'
    | '/employees'
    | '/cafe/edit/$cafeId'
    | '/employee/edit/$employeeId'
    | '/cafe/add'
    | '/employee/add'
  id:
    | '__root__'
    | '/'
    | '/cafes'
    | '/employees'
    | '/cafe/edit/$cafeId'
    | '/employee/edit/$employeeId'
    | '/cafe/add/'
    | '/employee/add/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafesRoute: typeof CafesRoute
  EmployeesRoute: typeof EmployeesRoute
  CafeEditCafeIdRoute: typeof CafeEditCafeIdRoute
  EmployeeEditEmployeeIdRoute: typeof EmployeeEditEmployeeIdRoute
  CafeAddIndexRoute: typeof CafeAddIndexRoute
  EmployeeAddIndexRoute: typeof EmployeeAddIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafesRoute: CafesRoute,
  EmployeesRoute: EmployeesRoute,
  CafeEditCafeIdRoute: CafeEditCafeIdRoute,
  EmployeeEditEmployeeIdRoute: EmployeeEditEmployeeIdRoute,
  CafeAddIndexRoute: CafeAddIndexRoute,
  EmployeeAddIndexRoute: EmployeeAddIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cafes",
        "/employees",
        "/cafe/edit/$cafeId",
        "/employee/edit/$employeeId",
        "/cafe/add/",
        "/employee/add/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cafes": {
      "filePath": "cafes.tsx"
    },
    "/employees": {
      "filePath": "employees.tsx"
    },
    "/cafe/edit/$cafeId": {
      "filePath": "cafe/edit/$cafeId.tsx"
    },
    "/employee/edit/$employeeId": {
      "filePath": "employee/edit/$employeeId.tsx"
    },
    "/cafe/add/": {
      "filePath": "cafe/add/index.tsx"
    },
    "/employee/add/": {
      "filePath": "employee/add/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
